name: Build Android APK

on:
  workflow_dispatch:

jobs:
  build:
    name: Build APK using Buildozer
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      # 🎯 اضافه شدن pexpect برای تایید خودکار لایسنس‌ها
      - name: Install modern system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y git zip unzip openjdk-17-jdk python3-pip python3-virtualenv autoconf libtool pkg-config zlib1g-dev libncurses5-dev libncursesw5-dev libtinfo6 cmake libffi-dev libssl-dev automake autopoint gettext
          pip install --upgrade pip
          pip install --upgrade buildozer cython virtualenv pexpect

      # 🎯 اضافه شدن yes | برای دور زدن هرگونه پرسش و پاسخ (y/n) در سرور
      - name: Build APK with Buildozer
        run: |
          yes | buildozer -v android debug

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ProtonScanner-APK
          path: bin/*.apk
